const COMPANY_MAP = {
  "3m": "MMM",
  "a. o. smith": "AOS",
  "aapl": "AAPL",
  "abbott": "ABT",
  "abbott laboratories": "ABT",
  "abbv": "ABBV",
  "abbvie": "ABBV",
  "abnb": "ABNB",
  "abt": "ABT",
  "accenture": "ACN",
  "acgl": "ACGL",
  "acn": "ACN",
  "adbe": "ADBE",
  "adi": "ADI",
  "adm": "ADM",
  "adobe": "ADBE",
  "adobe inc.": "ADBE",
  "adp": "ADP",
  "adsk": "ADSK",
  "advanced": "AMD",
  "advanced micro devices": "AMD",
  "aee": "AEE",
  "aep": "AEP",
  "aes": "AES",
  "aes corporation": "AES",
  "afl": "AFL",
  "aflac": "AFL",
  "agilent": "A",
  "agilent technologies": "A",
  "aig": "AIG",
  "air": "APD",
  "air products": "APD",
  "airbnb": "ABNB",
  "aiz": "AIZ",
  "ajg": "AJG",
  "akam": "AKAM",
  "akamai": "AKAM",
  "akamai technologies": "AKAM",
  "alb": "ALB",
  "albemarle": "ALB",
  "albemarle corporation": "ALB",
  "alexandria": "ARE",
  "alexandria real estate equities": "ARE",
  "algn": "ALGN",
  "align": "ALGN",
  "align technology": "ALGN",
  "all": "ALL",
  "alle": "ALLE",
  "allegion": "ALLE",
  "alliant": "LNT",
  "alliant energy": "LNT",
  "allstate": "ALL",
  "alphabet": "GOOGL",
  "alphabet inc.": "GOOGL",
  "alphabet inc. (class a)": "GOOGL",
  "alphabet inc. (class c)": "GOOG",
  "altria": "MO",
  "amat": "AMAT",
  "amazon": "AMZN",
  "amcor": "AMCR",
  "amcr": "AMCR",
  "amd": "AMD",
  "ame": "AME",
  "ameren": "AEE",
  "american": "AEP",
  "american electric power": "AEP",
  "american express": "AXP",
  "american international": "AIG",
  "american international group": "AIG",
  "american tower": "AMT",
  "american water works": "AWK",
  "ameriprise": "AMP",
  "ameriprise financial": "AMP",
  "ametek": "AME",
  "amex": "AXP",
  "amgen": "AMGN",
  "amgn": "AMGN",
  "amp": "AMP",
  "amphenol": "APH",
  "amt": "AMT",
  "amzn": "AMZN",
  "analog": "ADI",
  "analog devices": "ADI",
  "anet": "ANET",
  "anthem": "ELV",
  "anthropic": null,
  "aon": "AON",
  "aon plc": "AON",
  "aos": "AOS",
  "apa": "APA",
  "apa corporation": "APA",
  "apd": "APD",
  "aph": "APH",
  "apo": "APO",
  "apollo": "APO",
  "apollo global management": "APO",
  "app": "APP",
  "apple": "AAPL",
  "apple inc.": "AAPL",
  "applied": "AMAT",
  "applied materials": "AMAT",
  "applovin": "APP",
  "aptiv": "APTV",
  "aptv": "APTV",
  "arch": "ACGL",
  "arch capital": "ACGL",
  "arch capital group": "ACGL",
  "archer": "ADM",
  "archer daniels midland": "ADM",
  "are": "ARE",
  "ares": "ARES",
  "ares management": "ARES",
  "arista": "ANET",
  "arista networks": "ANET",
  "arthur": "AJG",
  "arthur j. gallagher": "AJG",
  "arthur j. gallagher & co.": "AJG",
  "asml": "ASML",
  "asml holding": "ASML",
  "assurant": "AIZ",
  "at&t": "T",
  "atmos": "ATO",
  "atmos energy": "ATO",
  "ato": "ATO",
  "att": "T",
  "autodesk": "ADSK",
  "automatic": "ADP",
  "automatic data processing": "ADP",
  "autozone": "AZO",
  "avalonbay": "AVB",
  "avalonbay communities": "AVB",
  "avb": "AVB",
  "avery": "AVY",
  "avery dennison": "AVY",
  "avgo": "AVGO",
  "avy": "AVY",
  "awk": "AWK",
  "axon": "AXON",
  "axon enterprise": "AXON",
  "axp": "AXP",
  "azo": "AZO",
  "ba": "BA",
  "bac": "BAC",
  "baker": "BKR",
  "baker hughes": "BKR",
  "ball": "BALL",
  "ball corporation": "BALL",
  "bank": "BAC",
  "bank of america": "BAC",
  "bax": "BAX",
  "baxter": "BAX",
  "baxter international": "BAX",
  "bby": "BBY",
  "bdx": "BDX",
  "becton": "BDX",
  "becton dickinson": "BDX",
  "ben": "BEN",
  "berkshire": "BRK.B",
  "berkshire hathaway": "BRK.B",
  "best": "BBY",
  "best buy": "BBY",
  "bf.b": "BF.B",
  "bg": "BG",
  "biib": "BIIB",
  "bio-techne": "TECH",
  "biogen": "BIIB",
  "bkng": "BKNG",
  "bkr": "BKR",
  "blackrock": "BLK",
  "blackstone": "BX",
  "blackstone inc.": "BX",
  "bldr": "BLDR",
  "blk": "BLK",
  "block": "XYZ",
  "block, inc.": "XYZ",
  "bmy": "BMY",
  "bny": "BNY",
  "bny mellon": "BNY",
  "boeing": "BA",
  "bofa": "BAC",
  "booking": "BKNG",
  "booking holdings": "BKNG",
  "boston": "BSX",
  "boston scientific": "BSX",
  "bp": "BP",
  "br": "BR",
  "bristol": "BMY",
  "bristol myers squibb": "BMY",
  "brk.b": "BRK.B",
  "bro": "BRO",
  "broadcom": "AVGO",
  "broadridge": "BR",
  "broadridge financial solutions": "BR",
  "brown": "BRO",
  "brown & brown": "BRO",
  "brown–forman": "BF.B",
  "bsx": "BSX",
  "builders": "BLDR",
  "builders firstsource": "BLDR",
  "bunge": "BG",
  "bunge global": "BG",
  "bx": "BX",
  "bxp": "BXP",
  "bxp, inc.": "BXP",
  "bytedance": null,
  "c.h.": "CHRW",
  "c.h. robinson": "CHRW",
  "cadence": "CDNS",
  "cadence design systems": "CDNS",
  "cag": "CAG",
  "cah": "CAH",
  "camden": "CPT",
  "camden property trust": "CPT",
  "campbell's": "CPB",
  "campbell's company (the)": "CPB",
  "capital": "COF",
  "capital one": "COF",
  "cardinal": "CAH",
  "cardinal health": "CAH",
  "carnival": "CCL",
  "carnival corporation": "CCL",
  "carr": "CARR",
  "carrier": "CARR",
  "carrier global": "CARR",
  "carvana": "CVNA",
  "casey's": "CASY",
  "casy": "CASY",
  "cat": "CAT",
  "caterpillar": "CAT",
  "caterpillar inc.": "CAT",
  "cb": "CB",
  "cboe": "CBOE",
  "cboe global markets": "CBOE",
  "cbre": "CBRE",
  "cbre group": "CBRE",
  "cci": "CCI",
  "ccl": "CCL",
  "cdns": "CDNS",
  "cdw": "CDW",
  "cdw corporation": "CDW",
  "ceg": "CEG",
  "cencora": "COR",
  "centene": "CNC",
  "centene corporation": "CNC",
  "centerpoint": "CNP",
  "centerpoint energy": "CNP",
  "cf": "CF",
  "cf industries": "CF",
  "cfg": "CFG",
  "charles": "CRL",
  "charles river laboratories": "CRL",
  "charles schwab": "SCHW",
  "charles schwab corporation": "SCHW",
  "charter": "CHTR",
  "charter communications": "CHTR",
  "chd": "CHD",
  "chevron": "CVX",
  "chevron corporation": "CVX",
  "chipotle": "CMG",
  "chipotle mexican grill": "CMG",
  "chrw": "CHRW",
  "chtr": "CHTR",
  "chubb": "CB",
  "chubb limited": "CB",
  "church": "CHD",
  "church & dwight": "CHD",
  "ci": "CI",
  "cien": "CIEN",
  "ciena": "CIEN",
  "cigna": "CI",
  "cincinnati": "CINF",
  "cincinnati financial": "CINF",
  "cinf": "CINF",
  "cintas": "CTAS",
  "cis": "CSCO",
  "cisco": "CSCO",
  "citi": "C",
  "citigroup": "C",
  "citizens": "CFG",
  "citizens financial": "CFG",
  "citizens financial group": "CFG",
  "cl": "CL",
  "clorox": "CLX",
  "clx": "CLX",
  "cmcsa": "CMCSA",
  "cme": "CME",
  "cme group": "CME",
  "cmg": "CMG",
  "cmi": "CMI",
  "cms": "CMS",
  "cms energy": "CMS",
  "cnc": "CNC",
  "cnp": "CNP",
  "coca-cola": "KO",
  "coca-cola company (the)": "KO",
  "cof": "COF",
  "cognizant": "CTSH",
  "coherent": "COHR",
  "coherent corp.": "COHR",
  "cohr": "COHR",
  "coin": "COIN",
  "coinbase": "COIN",
  "coke": "KO",
  "colgate-palmolive": "CL",
  "comcast": "CMCSA",
  "comfort": "FIX",
  "comfort systems usa": "FIX",
  "conagra": "CAG",
  "conagra brands": "CAG",
  "conocophillips": "COP",
  "consolidated": "ED",
  "consolidated edison": "ED",
  "constellation": "STZ",
  "constellation brands": "STZ",
  "constellation energy": "CEG",
  "coo": "COO",
  "cooper": "COO",
  "cooper companies (the)": "COO",
  "cop": "COP",
  "copart": "CPRT",
  "cor": "COR",
  "corning": "GLW",
  "corning inc.": "GLW",
  "corpay": "CPAY",
  "corteva": "CTVA",
  "cost": "COST",
  "costar": "CSGP",
  "costar group": "CSGP",
  "costco": "COST",
  "cpay": "CPAY",
  "cpb": "CPB",
  "cprt": "CPRT",
  "cpt": "CPT",
  "crh": "CRH",
  "crh plc": "CRH",
  "crl": "CRL",
  "crm": "CRM",
  "crowdstrike": "CRWD",
  "crown": "CCI",
  "crown castle": "CCI",
  "crwd": "CRWD",
  "csco": "CSCO",
  "csgp": "CSGP",
  "csx": "CSX",
  "csx corporation": "CSX",
  "ctas": "CTAS",
  "ctsh": "CTSH",
  "ctva": "CTVA",
  "cummins": "CMI",
  "cvna": "CVNA",
  "cvs": "CVS",
  "cvs health": "CVS",
  "cvx": "CVX",
  "d. r. horton": "DHI",
  "dal": "DAL",
  "danaher": "DHR",
  "danaher corporation": "DHR",
  "darden": "DRI",
  "darden restaurants": "DRI",
  "dash": "DASH",
  "databricks": null,
  "datadog": "DDOG",
  "davita": "DVA",
  "dd": "DD",
  "ddog": "DDOG",
  "de": "DE",
  "deck": "DECK",
  "deckers": "DECK",
  "deckers brands": "DECK",
  "deere": "DE",
  "deere &": "DE",
  "deere & company": "DE",
  "dell": "DELL",
  "dell technologies": "DELL",
  "delta": "DAL",
  "delta air lines": "DAL",
  "devon": "DVN",
  "devon energy": "DVN",
  "dexcom": "DXCM",
  "dg": "DG",
  "dgx": "DGX",
  "dhi": "DHI",
  "dhr": "DHR",
  "diamondback": "FANG",
  "diamondback energy": "FANG",
  "digital": "DLR",
  "digital realty": "DLR",
  "dis": "DIS",
  "disney": "DIS",
  "dlr": "DLR",
  "dltr": "DLTR",
  "doc": "DOC",
  "dollar": "DG",
  "dollar general": "DG",
  "dollar tree": "DLTR",
  "dominion": "D",
  "dominion energy": "D",
  "domino's": "DPZ",
  "doordash": "DASH",
  "dov": "DOV",
  "dover": "DOV",
  "dover corporation": "DOV",
  "dow": "DOW",
  "dow inc.": "DOW",
  "dpz": "DPZ",
  "dri": "DRI",
  "dte": "DTE",
  "dte energy": "DTE",
  "duk": "DUK",
  "duke": "DUK",
  "duke energy": "DUK",
  "dupont": "DD",
  "dva": "DVA",
  "dvn": "DVN",
  "dxcm": "DXCM",
  "ea": "EA",
  "eaton": "ETN",
  "eaton corporation": "ETN",
  "ebay": "EBAY",
  "ebay inc.": "EBAY",
  "echostar": "SATS",
  "ecl": "ECL",
  "ecolab": "ECL",
  "ed": "ED",
  "edison": "EIX",
  "edison international": "EIX",
  "edwards": "EW",
  "edwards lifesciences": "EW",
  "efx": "EFX",
  "eg": "EG",
  "eix": "EIX",
  "el": "EL",
  "electronic": "EA",
  "electronic arts": "EA",
  "elevance": "ELV",
  "elevance health": "ELV",
  "eli lilly": "LLY",
  "elv": "ELV",
  "emcor": "EME",
  "eme": "EME",
  "emerson": "EMR",
  "emerson electric": "EMR",
  "emr": "EMR",
  "entergy": "ETR",
  "eog": "EOG",
  "eog resources": "EOG",
  "eqix": "EQIX",
  "eqr": "EQR",
  "eqt": "EQT",
  "eqt corporation": "EQT",
  "equifax": "EFX",
  "equinix": "EQIX",
  "equity": "EQR",
  "equity residential": "EQR",
  "erie": "ERIE",
  "erie indemnity": "ERIE",
  "es": "ES",
  "ess": "ESS",
  "essex": "ESS",
  "essex property trust": "ESS",
  "estée": "EL",
  "estée lauder companies (the)": "EL",
  "etn": "ETN",
  "etr": "ETR",
  "everest": "EG",
  "everest group": "EG",
  "evergy": "EVRG",
  "eversource": "ES",
  "eversource energy": "ES",
  "evrg": "EVRG",
  "ew": "EW",
  "exc": "EXC",
  "exe": "EXE",
  "exelon": "EXC",
  "expand": "EXE",
  "expand energy": "EXE",
  "expd": "EXPD",
  "expe": "EXPE",
  "expedia": "EXPE",
  "expedia group": "EXPE",
  "expeditors": "EXPD",
  "expeditors international": "EXPD",
  "exr": "EXR",
  "extra": "EXR",
  "extra space storage": "EXR",
  "exxon": "XOM",
  "exxon mobil": "XOM",
  "exxonmobil": "XOM",
  "f5": "FFIV",
  "f5, inc.": "FFIV",
  "facebook": "META",
  "factset": "FDS",
  "fair": "FICO",
  "fair isaac": "FICO",
  "fang": "FANG",
  "fast": "FAST",
  "fastenal": "FAST",
  "fcx": "FCX",
  "fds": "FDS",
  "fdx": "FDX",
  "fdxf": "FDXF",
  "fe": "FE",
  "federal": "FRT",
  "federal realty investment trust": "FRT",
  "fedex": "FDX",
  "fedex freight": "FDXF",
  "ffiv": "FFIV",
  "fico": "FICO",
  "fidelity": "FIS",
  "fidelity national information services": "FIS",
  "fifth": "FITB",
  "fifth third ban": "FITB",
  "fifth third bancorp": "FITB",
  "first": "FSLR",
  "first solar": "FSLR",
  "firstenergy": "FE",
  "fis": "FIS",
  "fiserv": "FISV",
  "fisv": "FISV",
  "fitb": "FITB",
  "fix": "FIX",
  "ford": "F",
  "ford motor": "F",
  "ford motor company": "F",
  "fortinet": "FTNT",
  "fortive": "FTV",
  "fox": "FOXA",
  "fox corporation": "FOXA",
  "fox corporation (class a)": "FOXA",
  "fox corporation (class b)": "FOX",
  "foxa": "FOXA",
  "franklin": "BEN",
  "franklin resources": "BEN",
  "freeport-mcmoran": "FCX",
  "frt": "FRT",
  "fslr": "FSLR",
  "ftnt": "FTNT",
  "ftv": "FTV",
  "garmin": "GRMN",
  "gartner": "IT",
  "gd": "GD",
  "gddy": "GDDY",
  "ge": "GE",
  "ge aerospace": "GE",
  "ge healthcare": "GEHC",
  "ge vernova": "GEV",
  "gehc": "GEHC",
  "gen": "GEN",
  "gen digital": "GEN",
  "generac": "GNRC",
  "general": "GD",
  "general dynamics": "GD",
  "general electric": "GE",
  "general mills": "GIS",
  "general motors": "GM",
  "genuine": "GPC",
  "genuine parts": "GPC",
  "genuine parts company": "GPC",
  "gev": "GEV",
  "gild": "GILD",
  "gilead": "GILD",
  "gilead sciences": "GILD",
  "gis": "GIS",
  "gl": "GL",
  "global": "GPN",
  "global payments": "GPN",
  "globe": "GL",
  "globe life": "GL",
  "glw": "GLW",
  "gm": "GM",
  "gnrc": "GNRC",
  "godaddy": "GDDY",
  "goldman": "GS",
  "goldman sachs": "GS",
  "goog": "GOOG",
  "googl": "GOOGL",
  "google": "GOOGL",
  "gpc": "GPC",
  "gpn": "GPN",
  "grmn": "GRMN",
  "gs": "GS",
  "gww": "GWW",
  "hal": "HAL",
  "halliburton": "HAL",
  "hartford": "HIG",
  "hartford (the)": "HIG",
  "has": "HAS",
  "hasbro": "HAS",
  "hban": "HBAN",
  "hca": "HCA",
  "hca healthcare": "HCA",
  "hd": "HD",
  "healthpeak": "DOC",
  "healthpeak properties": "DOC",
  "henry": "HSIC",
  "henry schein": "HSIC",
  "hershey": "HSY",
  "hershey company (the)": "HSY",
  "hewlett": "HPE",
  "hewlett packard enterprise": "HPE",
  "hig": "HIG",
  "hii": "HII",
  "hilton": "HLT",
  "hilton worldwide": "HLT",
  "hlt": "HLT",
  "home": "HD",
  "home depot": "HD",
  "home depot (the)": "HD",
  "hon": "HON",
  "honda": "HMC",
  "honeywell": "HON",
  "hood": "HOOD",
  "hormel": "HRL",
  "hormel foods": "HRL",
  "host": "HST",
  "host hotels & resorts": "HST",
  "howmet": "HWM",
  "howmet aerospace": "HWM",
  "hp": "HPQ",
  "hp inc.": "HPQ",
  "hpe": "HPE",
  "hpq": "HPQ",
  "hrl": "HRL",
  "hsic": "HSIC",
  "hst": "HST",
  "hsy": "HSY",
  "hubb": "HUBB",
  "hubbell": "HUBB",
  "hubbell incorporated": "HUBB",
  "hum": "HUM",
  "humana": "HUM",
  "huntington": "HBAN",
  "huntington bancshares": "HBAN",
  "huntington ingalls industries": "HII",
  "hwm": "HWM",
  "ibkr": "IBKR",
  "ibm": "IBM",
  "ice": "ICE",
  "idex": "IEX",
  "idex corporation": "IEX",
  "idexx": "IDXX",
  "idexx laboratories": "IDXX",
  "idxx": "IDXX",
  "iex": "IEX",
  "iff": "IFF",
  "illinois": "ITW",
  "illinois tool works": "ITW",
  "incy": "INCY",
  "incyte": "INCY",
  "ingersoll": "IR",
  "ingersoll rand": "IR",
  "insulet": "PODD",
  "insulet corporation": "PODD",
  "intc": "INTC",
  "intel": "INTC",
  "interactive": "IBKR",
  "interactive brokers": "IBKR",
  "intercontinental": "ICE",
  "intercontinental exchange": "ICE",
  "international": "IFF",
  "international flavors & fragrances": "IFF",
  "international paper": "IP",
  "intu": "INTU",
  "intuit": "INTU",
  "intuitive": "ISRG",
  "intuitive surgical": "ISRG",
  "inves": "IVZ",
  "invesco": "IVZ",
  "invh": "INVH",
  "invitation": "INVH",
  "invitation homes": "INVH",
  "ip": "IP",
  "iqv": "IQV",
  "iqvia": "IQV",
  "ir": "IR",
  "irm": "IRM",
  "iron": "IRM",
  "iron mountain": "IRM",
  "isrg": "ISRG",
  "it": "IT",
  "itw": "ITW",
  "ivz": "IVZ",
  "j.b.": "JBHT",
  "j.b. hunt": "JBHT",
  "j.m.": "SJM",
  "j.m. smucker company (the)": "SJM",
  "j&j": "JNJ",
  "jabil": "JBL",
  "jack": "JKHY",
  "jack henry & associates": "JKHY",
  "jacobs": "J",
  "jacobs solutions": "J",
  "jbht": "JBHT",
  "jbl": "JBL",
  "jci": "JCI",
  "jkhy": "JKHY",
  "jnj": "JNJ",
  "johnson": "JNJ",
  "johnson & johnson": "JNJ",
  "johnson controls": "JCI",
  "jp morgan": "JPM",
  "jpm": "JPM",
  "jpmorgan": "JPM",
  "jpmorgan chase": "JPM",
  "kdp": "KDP",
  "kenvue": "KVUE",
  "keurig": "KDP",
  "keurig dr pepper": "KDP",
  "key": "KEY",
  "keycorp": "KEY",
  "keys": "KEYS",
  "keysight": "KEYS",
  "keysight technologies": "KEYS",
  "khc": "KHC",
  "kim": "KIM",
  "kimberly-clark": "KMB",
  "kimco": "KIM",
  "kimco realty": "KIM",
  "kinder": "KMI",
  "kinder morgan": "KMI",
  "kkr": "KKR",
  "kkr & co.": "KKR",
  "kla": "KLAC",
  "kla corporation": "KLAC",
  "klac": "KLAC",
  "kmb": "KMB",
  "kmi": "KMI",
  "ko": "KO",
  "kr": "KR",
  "kraft": "KHC",
  "kraft heinz": "KHC",
  "kroger": "KR",
  "kvue": "KVUE",
  "l3harris": "LHX",
  "lab": "LH",
  "labcorp": "LH",
  "lam": "LRCX",
  "lam research": "LRCX",
  "las": "LVS",
  "las vegas sands": "LVS",
  "ldos": "LDOS",
  "leidos": "LDOS",
  "len": "LEN",
  "lennar": "LEN",
  "lennox": "LII",
  "lennox international": "LII",
  "lh": "LH",
  "lhx": "LHX",
  "lii": "LII",
  "lilly": "LLY",
  "lilly (eli)": "LLY",
  "lin": "LIN",
  "linde": "LIN",
  "linde plc": "LIN",
  "lite": "LITE",
  "live": "LYV",
  "live nation entertainment": "LYV",
  "lly": "LLY",
  "lmt": "LMT",
  "lnt": "LNT",
  "lockheed": "LMT",
  "lockheed martin": "LMT",
  "loews": "L",
  "loews corporation": "L",
  "low": "LOW",
  "lowe's": "LOW",
  "lowes": "LOW",
  "lrcx": "LRCX",
  "lulu": "LULU",
  "lululemon": "LULU",
  "lululemon athletica": "LULU",
  "lumentum": "LITE",
  "luv": "LUV",
  "lvs": "LVS",
  "lyb": "LYB",
  "lyft": "LYFT",
  "lyondellbasell": "LYB",
  "lyv": "LYV",
  "m&t": "MTB",
  "m&t bank": "MTB",
  "ma": "MA",
  "maa": "MAA",
  "mar": "MAR",
  "marathon": "MPC",
  "marathon petroleum": "MPC",
  "marriott": "MAR",
  "marriott international": "MAR",
  "marsh": "MRSH",
  "marsh mclennan": "MRSH",
  "martin": "MLM",
  "martin marietta materials": "MLM",
  "mas": "MAS",
  "masco": "MAS",
  "mastercard": "MA",
  "mccormick": "MKC",
  "mccormick &": "MKC",
  "mccormick & company": "MKC",
  "mcd": "MCD",
  "mcdonald's": "MCD",
  "mcdonalds": "MCD",
  "mchp": "MCHP",
  "mck": "MCK",
  "mckesson": "MCK",
  "mckesson corporation": "MCK",
  "mco": "MCO",
  "mdlz": "MDLZ",
  "mdt": "MDT",
  "medtronic": "MDT",
  "merck": "MRK",
  "merck & co.": "MRK",
  "met": "MET",
  "meta": "META",
  "meta platforms": "META",
  "metlife": "MET",
  "mettler": "MTD",
  "mettler toledo": "MTD",
  "mgm": "MGM",
  "mgm resorts": "MGM",
  "microchip": "MCHP",
  "microchip technology": "MCHP",
  "micron": "MU",
  "micron technology": "MU",
  "microsoft": "MSFT",
  "mid-america": "MAA",
  "mid-america apartment communities": "MAA",
  "mkc": "MKC",
  "mlm": "MLM",
  "mmm": "MMM",
  "mnst": "MNST",
  "mo": "MO",
  "moderna": "MRNA",
  "molson": "TAP",
  "molson coors beverage": "TAP",
  "molson coors beverage company": "TAP",
  "mondelez": "MDLZ",
  "mondelez international": "MDLZ",
  "monolithic": "MPWR",
  "monolithic power systems": "MPWR",
  "monster": "MNST",
  "monster beverage": "MNST",
  "moody's": "MCO",
  "moody's corporation": "MCO",
  "morgan": "MS",
  "morgan stanley": "MS",
  "mos": "MOS",
  "mosaic": "MOS",
  "mosaic company (the)": "MOS",
  "motorola": "MSI",
  "motorola solutions": "MSI",
  "mpc": "MPC",
  "mpwr": "MPWR",
  "mrk": "MRK",
  "mrna": "MRNA",
  "mrsh": "MRSH",
  "ms": "MS",
  "msci": "MSCI",
  "msci inc.": "MSCI",
  "msft": "MSFT",
  "msi": "MSI",
  "mtb": "MTB",
  "mtd": "MTD",
  "mu": "MU",
  "nasdaq": "NDAQ",
  "nasdaq, inc.": "NDAQ",
  "nclh": "NCLH",
  "ndaq": "NDAQ",
  "ndsn": "NDSN",
  "nee": "NEE",
  "nem": "NEM",
  "nestle": "NSRGY",
  "netapp": "NTAP",
  "netflix": "NFLX",
  "newmont": "NEM",
  "news": "NWSA",
  "news corp": "NWSA",
  "news corp (class a)": "NWSA",
  "news corp (class b)": "NWS",
  "nextera": "NEE",
  "nextera energy": "NEE",
  "nflx": "NFLX",
  "ni": "NI",
  "nike": "NKE",
  "nike, inc.": "NKE",
  "nintendo": "NTDOY",
  "nisource": "NI",
  "nke": "NKE",
  "noc": "NOC",
  "nordson": "NDSN",
  "nordson corporation": "NDSN",
  "norfolk": "NSC",
  "norfolk southern": "NSC",
  "northern": "NTRS",
  "northern trust": "NTRS",
  "northrop": "NOC",
  "northrop grumman": "NOC",
  "norwegian": "NCLH",
  "norwegian cruise line": "NCLH",
  "norwegian cruise line holdings": "NCLH",
  "now": "NOW",
  "nrg": "NRG",
  "nrg energy": "NRG",
  "nsc": "NSC",
  "ntap": "NTAP",
  "ntrs": "NTRS",
  "nucor": "NUE",
  "nue": "NUE",
  "nvda": "NVDA",
  "nvidia": "NVDA",
  "nvr": "NVR",
  "nvr, inc.": "NVR",
  "nws": "NWS",
  "nwsa": "NWSA",
  "nxp": "NXPI",
  "nxp semiconductors": "NXPI",
  "nxpi": "NXPI",
  "o’reilly": "ORLY",
  "o’reilly automotive": "ORLY",
  "occidental": "OXY",
  "occidental petroleum": "OXY",
  "odfl": "ODFL",
  "oke": "OKE",
  "old": "ODFL",
  "old dominion": "ODFL",
  "omc": "OMC",
  "omnicom": "OMC",
  "omnicom group": "OMC",
  "on": "ON",
  "on semiconductor": "ON",
  "oneok": "OKE",
  "openai": null,
  "oracle": "ORCL",
  "oracle corporation": "ORCL",
  "orcl": "ORCL",
  "orly": "ORLY",
  "otis": "OTIS",
  "otis worldwide": "OTIS",
  "oxy": "OXY",
  "p&g": "PG",
  "paccar": "PCAR",
  "packaging": "PKG",
  "packaging corporation of america": "PKG",
  "palantir": "PLTR",
  "palantir technologies": "PLTR",
  "palo": "PANW",
  "palo alto networks": "PANW",
  "panw": "PANW",
  "paramount": "PSKY",
  "paramount skydance": "PSKY",
  "paramount skydance corporation": "PSKY",
  "parker": "PH",
  "parker hannifin": "PH",
  "paychex": "PAYX",
  "paypal": "PYPL",
  "payx": "PAYX",
  "pcar": "PCAR",
  "pcg": "PCG",
  "peg": "PEG",
  "pentair": "PNR",
  "pep": "PEP",
  "pepsi": "PEP",
  "pepsico": "PEP",
  "pfe": "PFE",
  "pfg": "PFG",
  "pfizer": "PFE",
  "pg": "PG",
  "pg&e": "PCG",
  "pg&e corporation": "PCG",
  "pgr": "PGR",
  "ph": "PH",
  "philip": "PM",
  "philip morris international": "PM",
  "phillips": "PSX",
  "phillips 66": "PSX",
  "phm": "PHM",
  "pinnacle": "PNW",
  "pinnacle west capital": "PNW",
  "pkg": "PKG",
  "pld": "PLD",
  "pltr": "PLTR",
  "pm": "PM",
  "pnc": "PNC",
  "pnc financial services": "PNC",
  "pnr": "PNR",
  "pnw": "PNW",
  "podd": "PODD",
  "pool": "POOL",
  "pool corporation": "POOL",
  "ppg": "PPG",
  "ppg industries": "PPG",
  "ppl": "PPL",
  "ppl corporation": "PPL",
  "principal": "PFG",
  "principal financial": "PFG",
  "principal financial group": "PFG",
  "procter": "PG",
  "procter & gamble": "PG",
  "progressive": "PGR",
  "progressive corporation": "PGR",
  "prologis": "PLD",
  "pru": "PRU",
  "prudential": "PRU",
  "prudential financial": "PRU",
  "psa": "PSA",
  "psky": "PSKY",
  "psx": "PSX",
  "ptc": "PTC",
  "ptc inc.": "PTC",
  "public": "PEG",
  "public service enterprise": "PEG",
  "public service enterprise group": "PEG",
  "public storage": "PSA",
  "pulte": "PHM",
  "pultegroup": "PHM",
  "pwr": "PWR",
  "pypl": "PYPL",
  "qcom": "QCOM",
  "qnity": "Q",
  "qnity electronics": "Q",
  "qualcomm": "QCOM",
  "quanta": "PWR",
  "quanta services": "PWR",
  "quest": "DGX",
  "quest diagnostics": "DGX",
  "ralph": "RL",
  "ralph lauren": "RL",
  "ralph lauren corporation": "RL",
  "raymond": "RJF",
  "raymond james financial": "RJF",
  "raytheon": "RTX",
  "rcl": "RCL",
  "realty": "O",
  "realty income": "O",
  "reg": "REG",
  "regency": "REG",
  "regency centers": "REG",
  "regeneron": "REGN",
  "regeneron pharmaceuticals": "REGN",
  "regions": "RF",
  "regions financial": "RF",
  "regions financial corporation": "RF",
  "regn": "REGN",
  "republic": "RSG",
  "republic services": "RSG",
  "resmed": "RMD",
  "revvity": "RVTY",
  "rf": "RF",
  "rjf": "RJF",
  "rl": "RL",
  "rmd": "RMD",
  "robinhood": "HOOD",
  "robinhood markets": "HOOD",
  "rockwell": "ROK",
  "rockwell automation": "ROK",
  "rok": "ROK",
  "rol": "ROL",
  "rollins": "ROL",
  "rollins, inc.": "ROL",
  "rop": "ROP",
  "roper": "ROP",
  "roper technologies": "ROP",
  "ross": "ROST",
  "ross stores": "ROST",
  "rost": "ROST",
  "royal": "RCL",
  "royal caribbean": "RCL",
  "royal caribbean group": "RCL",
  "royal dutch shell": "SHEL",
  "rsg": "RSG",
  "rtx": "RTX",
  "rtx corporation": "RTX",
  "rvty": "RVTY",
  "s&p": "SPGI",
  "s&p global": "SPGI",
  "salesforce": "CRM",
  "samsung": "SSNLF",
  "samsung electronics": "SSNLF",
  "sandisk": "SNDK",
  "sap": "SAP",
  "sats": "SATS",
  "sba": "SBAC",
  "sba communications": "SBAC",
  "sbac": "SBAC",
  "sbux": "SBUX",
  "schlumberger": "SLB",
  "schw": "SCHW",
  "seagate": "STX",
  "seagate technology": "STX",
  "sempra": "SRE",
  "servicenow": "NOW",
  "shell": "SHEL",
  "sherwin-williams": "SHW",
  "shopify": "SHOP",
  "shw": "SHW",
  "siemens": "SIEGY",
  "simon": "SPG",
  "simon property": "SPG",
  "simon property group": "SPG",
  "sjm": "SJM",
  "skyworks": "SWKS",
  "skyworks solutions": "SWKS",
  "slb": "SLB",
  "smci": "SMCI",
  "smurfit": "SW",
  "smurfit westrock": "SW",
  "sna": "SNA",
  "snap-on": "SNA",
  "sndk": "SNDK",
  "snowflake": "SNOW",
  "snps": "SNPS",
  "so": "SO",
  "solv": "SOLV",
  "solventum": "SOLV",
  "sony": "SONY",
  "southern": "SO",
  "southern company": "SO",
  "southwest": "LUV",
  "southwest airlines": "LUV",
  "spacex": null,
  "spg": "SPG",
  "spgi": "SPGI",
  "sre": "SRE",
  "stanley": "SWK",
  "stanley black & decker": "SWK",
  "starbucks": "SBUX",
  "state": "STT",
  "state street": "STT",
  "state street corporation": "STT",
  "ste": "STE",
  "steel": "STLD",
  "steel dynamics": "STLD",
  "steris": "STE",
  "stld": "STLD",
  "stripe": null,
  "stryker": "SYK",
  "stryker corporation": "SYK",
  "stt": "STT",
  "stx": "STX",
  "stz": "STZ",
  "supermicro": "SMCI",
  "sw": "SW",
  "swk": "SWK",
  "swks": "SWKS",
  "syf": "SYF",
  "syk": "SYK",
  "synchrony": "SYF",
  "synchrony financial": "SYF",
  "synopsys": "SNPS",
  "sys": "SYY",
  "sysco": "SYY",
  "syy": "SYY",
  "t-mobile": "TMUS",
  "t-mobile us": "TMUS",
  "t. rowe price": "TROW",
  "taiwan semiconductor": "TSM",
  "taiwan semiconductor manufacturing": "TSM",
  "take-two": "TTWO",
  "take-two interactive": "TTWO",
  "tap": "TAP",
  "tapestry": "TPR",
  "tapestry, inc.": "TPR",
  "targa": "TRGP",
  "targa resources": "TRGP",
  "target": "TGT",
  "target corporation": "TGT",
  "tdg": "TDG",
  "tdy": "TDY",
  "te connectivity": "TEL",
  "tech": "TECH",
  "tel": "TEL",
  "teledyne": "TDY",
  "teledyne technologies": "TDY",
  "ter": "TER",
  "teradyne": "TER",
  "tesla": "TSLA",
  "tesla, inc.": "TSLA",
  "texas": "TXN",
  "texas instruments": "TXN",
  "texas pacific land": "TPL",
  "texas pacific land corporation": "TPL",
  "textron": "TXT",
  "tfc": "TFC",
  "tgt": "TGT",
  "thermo": "TMO",
  "thermo fisher scientific": "TMO",
  "tiktok": null,
  "tjx": "TJX",
  "tjx companies": "TJX",
  "tko": "TKO",
  "tko group": "TKO",
  "tko group holdings": "TKO",
  "tmo": "TMO",
  "tmus": "TMUS",
  "total": "TTE",
  "totalenergies": "TTE",
  "toyota": "TM",
  "toyota motor": "TM",
  "tpl": "TPL",
  "tpr": "TPR",
  "tractor": "TSCO",
  "tractor supply": "TSCO",
  "trade": "TTD",
  "trade desk (the)": "TTD",
  "trane": "TT",
  "trane technologies": "TT",
  "transdigm": "TDG",
  "transdigm group": "TDG",
  "travelers": "TRV",
  "travelers companies (the)": "TRV",
  "trgp": "TRGP",
  "trimble": "TRMB",
  "trimble inc.": "TRMB",
  "trmb": "TRMB",
  "trow": "TROW",
  "truist": "TFC",
  "truist financial": "TFC",
  "trv": "TRV",
  "tsco": "TSCO",
  "tsla": "TSLA",
  "tsmc": "TSM",
  "tsn": "TSN",
  "tt": "TT",
  "ttd": "TTD",
  "ttwo": "TTWO",
  "txn": "TXN",
  "txt": "TXT",
  "tyl": "TYL",
  "tyler": "TYL",
  "tyler technologies": "TYL",
  "tyson": "TSN",
  "tyson foods": "TSN",
  "u.s.": "USB",
  "u.s. ban": "USB",
  "u.s. bancorp": "USB",
  "ual": "UAL",
  "uber": "UBER",
  "udr": "UDR",
  "udr, inc.": "UDR",
  "uhs": "UHS",
  "ulta": "ULTA",
  "ulta beauty": "ULTA",
  "unh": "UNH",
  "unilever": "UL",
  "union": "UNP",
  "union pacific": "UNP",
  "union pacific corporation": "UNP",
  "united": "UAL",
  "united airlines": "UAL",
  "united airlines holdings": "UAL",
  "united parcel service": "UPS",
  "united rentals": "URI",
  "unitedhealth": "UNH",
  "unitedhealth group": "UNH",
  "universal": "UHS",
  "universal health services": "UHS",
  "unp": "UNP",
  "ups": "UPS",
  "uri": "URI",
  "usb": "USB",
  "valero": "VLO",
  "valero energy": "VLO",
  "veev": "VEEV",
  "veeva": "VEEV",
  "veeva systems": "VEEV",
  "ventas": "VTR",
  "veralto": "VLTO",
  "verisign": "VRSN",
  "verisk": "VRSK",
  "verisk analytics": "VRSK",
  "verizon": "VZ",
  "vertex": "VRTX",
  "vertex pharmaceuticals": "VRTX",
  "vertiv": "VRT",
  "viatris": "VTRS",
  "vici": "VICI",
  "vici properties": "VICI",
  "visa": "V",
  "visa inc.": "V",
  "vistra": "VST",
  "vistra corp.": "VST",
  "vlo": "VLO",
  "vlto": "VLTO",
  "vmc": "VMC",
  "vrsk": "VRSK",
  "vrsn": "VRSN",
  "vrt": "VRT",
  "vrtx": "VRTX",
  "vst": "VST",
  "vtr": "VTR",
  "vtrs": "VTRS",
  "vulcan": "VMC",
  "vulcan materials": "VMC",
  "vulcan materials company": "VMC",
  "vz": "VZ",
  "w. r. berkley": "WRB",
  "w. r. berkley corporation": "WRB",
  "w. w. grainger": "GWW",
  "wab": "WAB",
  "wabtec": "WAB",
  "wal-mart": "WMT",
  "walmart": "WMT",
  "walt": "DIS",
  "walt disney": "DIS",
  "walt disney company (the)": "DIS",
  "warner": "WBD",
  "warner bros. discovery": "WBD",
  "waste": "WM",
  "waste management": "WM",
  "wat": "WAT",
  "waters": "WAT",
  "waters corporation": "WAT",
  "wbd": "WBD",
  "wday": "WDAY",
  "wdc": "WDC",
  "wec": "WEC",
  "wec energy": "WEC",
  "wec energy group": "WEC",
  "well": "WELL",
  "wells": "WFC",
  "wells fargo": "WFC",
  "welltower": "WELL",
  "west": "WST",
  "west pharmaceutical services": "WST",
  "western": "WDC",
  "western digital": "WDC",
  "weyerhaeuser": "WY",
  "wfc": "WFC",
  "williams": "WMB",
  "williams companies": "WMB",
  "williams-sonoma": "WSM",
  "williams-sonoma, inc.": "WSM",
  "willis": "WTW",
  "willis towers watson": "WTW",
  "wm": "WM",
  "wmb": "WMB",
  "wmt": "WMT",
  "workday": "WDAY",
  "workday, inc.": "WDAY",
  "wrb": "WRB",
  "wsm": "WSM",
  "wst": "WST",
  "wtw": "WTW",
  "wy": "WY",
  "wynn": "WYNN",
  "wynn resorts": "WYNN",
  "xai": null,
  "xcel": "XEL",
  "xcel energy": "XEL",
  "xel": "XEL",
  "xom": "XOM",
  "xyl": "XYL",
  "xylem": "XYL",
  "xylem inc.": "XYL",
  "xyz": "XYZ",
  "yum": "YUM",
  "yum!": "YUM",
  "yum! brands": "YUM",
  "zbh": "ZBH",
  "zbra": "ZBRA",
  "zebra": "ZBRA",
  "zebra technologies": "ZBRA",
  "zimmer": "ZBH",
  "zimmer biomet": "ZBH",
  "zoetis": "ZTS",
  "zts": "ZTS",
};
